### PR TITLE
MANIFEST.in: Add tests, LICENSE, etc

### PR DESCRIPTION
**Pull request by jayvdb**
Also forces inclusion of LICENSE in wheels.

Closes https://github.com/berdario/pew/issues/202

### CODE REVIEW

**Comment by pfmoore** [comment]
One thought - what's the project policy on including tests in the sdist? (We don't include them in pip, and in general I don't see the benefit, but I'm happy to follow project policy here).

**Comment by tjanez** [comment]
> One thought - what's the project policy on including tests in the sdist? (We don't include them in pip, and in general I don't see the benefit, but I'm happy to follow project policy here).

Based on https://github.com/berdario/pew/issues/202#issuecomment-483076250, I would say the answer is yes.

**Comment by pfmoore** [comment]
> Based on #202 (comment), I would say the answer is yes.

Cool. I don't have a strong opinion here. Does this PR correctly exclude the files noted in that comment? I haven't checked myself.

**Comment by tjanez** [comment]
> Cool. I don't have a strong opinion here. Does this PR correctly exclude the files noted in that comment? I haven't checked myself.

I took me by surprise, but the changes in this PR are no longer needed:

1. The `LICENSE` file has already been included in the wheel automatically (see [pew-1.2.0-py2.py3-none-any.whl](https://files.pythonhosted.org/packages/51/f7/ce786502ba49f2a2fb867b7219afd9fe4cb0ca892de9c280a8457ed40972/pew-1.2.0-py2.py3-none-any.whl)).

2. The `test/test*` files are also automatically included in the sdist (I tested with Python 3.7 on Fedora 31):
```
[tadej@toronto pew (master)]$ python setup.py sdist
running sdist
running egg_info
writing pew.egg-info/PKG-INFO
writing dependency_links to pew.egg-info/dependency_links.txt
writing entry points to pew.egg-info/entry_points.txt
writing requirements to pew.egg-info/requires.txt
writing top-level names to pew.egg-info/top_level.txt
reading manifest file 'pew.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found under directory 'pew'
writing manifest file 'pew.egg-info/SOURCES.txt'
running check
creating pew-1.2.0
creating pew-1.2.0/pew
creating pew-1.2.0/pew.egg-info
creating pew-1.2.0/pew/shell_config
creating pew-1.2.0/tests
creating pew-1.2.0/tests/testpackage
creating pew-1.2.0/tests/testpackage/build
creating pew-1.2.0/tests/testpackage/build/scripts-3.7
creating pew-1.2.0/tests/testpackage/build/scripts-3.8
copying files to pew-1.2.0...
copying LICENSE -> pew-1.2.0
copying MANIFEST.in -> pew-1.2.0
copying README.md -> pew-1.2.0
copying requirements.txt -> pew-1.2.0
copying setup.cfg -> pew-1.2.0
copying setup.py -> pew-1.2.0
copying pew/__init__.py -> pew-1.2.0/pew
copying pew/__main__.py -> pew-1.2.0/pew
copying pew/_print_utils.py -> pew-1.2.0/pew
copying pew/_utils.py -> pew-1.2.0/pew
copying pew/pew.py -> pew-1.2.0/pew
copying pew.egg-info/PKG-INFO -> pew-1.2.0/pew.egg-info
copying pew.egg-info/SOURCES.txt -> pew-1.2.0/pew.egg-info
copying pew.egg-info/dependency_links.txt -> pew-1.2.0/pew.egg-info
copying pew.egg-info/entry_points.txt -> pew-1.2.0/pew.egg-info
copying pew.egg-info/not-zip-safe -> pew-1.2.0/pew.egg-info
copying pew.egg-info/requires.txt -> pew-1.2.0/pew.egg-info
copying pew.egg-info/top_level.txt -> pew-1.2.0/pew.egg-info
copying pew/shell_config/_pew -> pew-1.2.0/pew/shell_config
copying pew/shell_config/complete.bash -> pew-1.2.0/pew/shell_config
copying pew/shell_config/complete.fish -> pew-1.2.0/pew/shell_config
copying pew/shell_config/complete.zsh -> pew-1.2.0/pew/shell_config
copying pew/shell_config/complete_deploy -> pew-1.2.0/pew/shell_config
copying pew/shell_config/init.bash -> pew-1.2.0/pew/shell_config
copying pew/shell_config/init.fish -> pew-1.2.0/pew/shell_config
copying pew/shell_config/init.zsh -> pew-1.2.0/pew/shell_config
copying tests/conftest.py -> pew-1.2.0/tests
copying tests/test_cp.py -> pew-1.2.0/tests
copying tests/test_dir.py -> pew-1.2.0/tests
copying tests/test_getproject.py -> pew-1.2.0/tests
copying tests/test_in.py -> pew-1.2.0/tests
copying tests/test_install.py -> pew-1.2.0/tests
copying tests/test_ls.py -> pew-1.2.0/tests
copying tests/test_mktmpenv.py -> pew-1.2.0/tests
copying tests/test_mkvirtualenv.py -> pew-1.2.0/tests
copying tests/test_pew.py -> pew-1.2.0/tests
copying tests/test_print_utils.py -> pew-1.2.0/tests
copying tests/test_project.py -> pew-1.2.0/tests
copying tests/test_restore.py -> pew-1.2.0/tests
copying tests/test_rmvirtualenv.py -> pew-1.2.0/tests
copying tests/test_setproject.py -> pew-1.2.0/tests
copying tests/test_wipe.py -> pew-1.2.0/tests
copying tests/test_workon.py -> pew-1.2.0/tests
copying tests/utils.py -> pew-1.2.0/tests
copying tests/testpackage/setup.py -> pew-1.2.0/tests/testpackage
copying tests/testpackage/testscript.py -> pew-1.2.0/tests/testpackage
copying tests/testpackage/build/scripts-3.7/testscript.py -> pew-1.2.0/tests/testpackage/build/scripts-3.7
copying tests/testpackage/build/scripts-3.8/testscript.py -> pew-1.2.0/tests/testpackage/build/scripts-3.8
Writing pew-1.2.0/setup.cfg
Creating tar archive
removing 'pew-1.2.0' (and everything under it)
```

  And this appears to be expected since the [Python Packaging User Guide mentions this](https://packaging.python.org/guides/using-manifest-in/#how-files-are-included-in-an-sdist) when explaining which files get included in an sdist:
  > all files matching the pattern `test/test*.py`

So, I think this one and #202 can be closed.

**Comment by jayvdb** [comment]
The PR doesnt attempt to exclude what I guess are build/test by-products, but it doesnt include most of those files.

**Comment by jayvdb** [comment]
Re automatic, setuptools has long automatically done some stuff, but even so many times the sdist on PyPI ends up without LICENSE files, etc.  I could try to guess what went wrong, or just explicitly declare that these files need to be included.

`test/test*.py` does not equal `tests/test*.py` (extra `s`), so something strange is happening there.

**Comment by tjanez** [comment]
> Re automatic, setuptools has long automatically done some stuff, but even so many times the sdist on PyPI ends up without LICENSE files, etc. I could try to guess what went wrong, or just explicitly declare that these files need to be included.

Agreed.

> `test/test*.py` does not equal `tests/test*.py` (extra `s`), so something strange is happening there.

Apparently, I didn't purge `pew.egg-info` between trying out your PR and building sdist on `master`.

If I purge `pew.egg-info`, then the `test/test*.py` files (+ `requirements.txt` and `LICENSE` files) are not included when building an sdist on the `master` branch:
```
[tadej@toronto pew (master)]$ rm -rf pew.egg-info/
[tadej@toronto pew (master)]$ python setup.py sdist
running sdist
running egg_info
creating pew.egg-info
writing pew.egg-info/PKG-INFO
writing dependency_links to pew.egg-info/dependency_links.txt
writing entry points to pew.egg-info/entry_points.txt
writing requirements to pew.egg-info/requires.txt
writing top-level names to pew.egg-info/top_level.txt
writing manifest file 'pew.egg-info/SOURCES.txt'
reading manifest file 'pew.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found under directory 'pew'
writing manifest file 'pew.egg-info/SOURCES.txt'
running check
creating pew-1.2.0
creating pew-1.2.0/pew
creating pew-1.2.0/pew.egg-info
creating pew-1.2.0/pew/shell_config
copying files to pew-1.2.0...
copying MANIFEST.in -> pew-1.2.0
copying README.md -> pew-1.2.0
copying setup.cfg -> pew-1.2.0
copying setup.py -> pew-1.2.0
copying pew/__init__.py -> pew-1.2.0/pew
copying pew/__main__.py -> pew-1.2.0/pew
copying pew/_print_utils.py -> pew-1.2.0/pew
copying pew/_utils.py -> pew-1.2.0/pew
copying pew/pew.py -> pew-1.2.0/pew
copying pew.egg-info/PKG-INFO -> pew-1.2.0/pew.egg-info
copying pew.egg-info/SOURCES.txt -> pew-1.2.0/pew.egg-info
copying pew.egg-info/dependency_links.txt -> pew-1.2.0/pew.egg-info
copying pew.egg-info/entry_points.txt -> pew-1.2.0/pew.egg-info
copying pew.egg-info/not-zip-safe -> pew-1.2.0/pew.egg-info
copying pew.egg-info/requires.txt -> pew-1.2.0/pew.egg-info
copying pew.egg-info/top_level.txt -> pew-1.2.0/pew.egg-info
copying pew/shell_config/_pew -> pew-1.2.0/pew/shell_config
copying pew/shell_config/complete.bash -> pew-1.2.0/pew/shell_config
copying pew/shell_config/complete.fish -> pew-1.2.0/pew/shell_config
copying pew/shell_config/complete.zsh -> pew-1.2.0/pew/shell_config
copying pew/shell_config/complete_deploy -> pew-1.2.0/pew/shell_config
copying pew/shell_config/init.bash -> pew-1.2.0/pew/shell_config
copying pew/shell_config/init.fish -> pew-1.2.0/pew/shell_config
copying pew/shell_config/init.zsh -> pew-1.2.0/pew/shell_config
Writing pew-1.2.0/setup.cfg
Creating tar archive
removing 'pew-1.2.0' (and everything under it)
```

**Comment by tjanez** [comment]
> Does this PR correctly exclude the files noted in that comment? I haven't checked myself.

My test shows that it does. Here is the diff between sdist built from `master` and sdist build from this PR:

```
[tadej@toronto dist (sdist-tests)]$ diff --brief pew-1.2.0-master pew-1.2.0-PR
Only in pew-1.2.0-PR: LICENSE
Files pew-1.2.0-master/MANIFEST.in and pew-1.2.0-PR/MANIFEST.in differ
Common subdirectories: pew-1.2.0-master/pew and pew-1.2.0-PR/pew
Common subdirectories: pew-1.2.0-master/pew.egg-info and pew-1.2.0-PR/pew.egg-info
Only in pew-1.2.0-PR: requirements.txt
Files pew-1.2.0-master/setup.cfg and pew-1.2.0-PR/setup.cfg differ
Only in pew-1.2.0-PR: tests
[tadej@toronto dist (sdist-tests)]$ tree pew-1.2.0-PR/tests
pew-1.2.0-PR/tests
├── conftest.py
├── test_cp.py
├── test_dir.py
├── test_getproject.py
├── test_in.py
├── test_install.py
├── test_ls.py
├── test_mktmpenv.py
├── test_mkvirtualenv.py
├── testpackage
│   ├── build
│   │   ├── scripts-3.7
│   │   │   └── testscript.py
│   │   └── scripts-3.8
│   │       └── testscript.py
│   ├── setup.py
│   └── testscript.py
├── test_pew.py
├── test_print_utils.py
├── test_project.py
├── test_restore.py
├── test_rmvirtualenv.py
├── test_setproject.py
├── test_wipe.py
├── test_workon.py
└── utils.py

4 directories, 22 files
```

**Pull request merged**
