### PR TITLE
Changes to add Python 3.7 support

### PR DESCRIPTION
**Pull request by pfmoore**

### CODE REVIEW

**Comment by pfmoore** [comment]
Hi, this PR unpins psutil, allowing installs for Python 3.7 on Windows without needing a compiler (psutil don't provide binaries of old versions for new Pythons), as well as adding Python 3.7 to CI.

I had to drop Python 3.3 from the CI, as many of pew's dependencies have now dropped Python 3.3 support, and I wasn't sure how worthwhile it would be to chase all the dependencies down and pin them to older versions. If you need me to do that I probably can.

**Comment by pfmoore** [comment]
@berdario ping...

**Comment by pfmoore** [comment]
@berdario Another ping. Any chance of getting this merged?

**Comment by berdario** [comment]
Merged!

Thanks a lot, and also for chasing... 

triaging and working on Pew's contributions is on my todo list, but along with a bunch of other things it keeps getting pushed back. It's now 1 year since I last worked on Pew :/

Lots of things happened: a breakup, travelled to a new continent, change role/team/office and finally moved home... 

I'm finally using Python again in my new team, though it's [Bazel](https://bazel.build/) and vendoring, instead of setuptools and pip, so Pew won't see much use here.

**Comment by termux-io** [comment]
`[Https://nintendo8dsswitch.com](Https://zionism.biz)`

**Pull request merged**
