### PR TITLE
Add support for loading environment variables from .inve.ini file

### PR DESCRIPTION
**Pull request by DanMayhem**
I had a similar use case to Pull Request #36. I reimplemented @rraval's changes against the latest codebase and added some tests.

I'm also interested in adding adding some commands to pew to manage environment variables within a virtualenv. E.g.
pew setvar env1 VariableName VariableValue

### CODE REVIEW

**Comment by rraval** [comment]
Hey @DanMayhem, thanks for bringing my old PR up to speed.

I've been using a `.inve.ini` to inject variables into my pew environments, but the more I think about it, the cruftier it seems. The string interpolation is crufty: trying to interpolate a variable that does not exist simply passes it along instead of erroring out or being replaced by the empty string. Overall, the INI setup seems too focused on injecting a simple set of variables without any support for logic or other more complicated setups.

I think the approach in #3 is actually the way to move forward. Allow the user to define a python module somewhere under `$VIRTUAL_ENV` that pew can source. pew can just define a number of function names that it calls as hooks, and the `inve` hook can simply inject things into `os.environ` to get all the functionality in the INI approach.

@berdario thoughts?

**Comment by berdario** [comment]
Thanks!

In the meanwhile, I asked my friend who used virtualenvwrapper with hooks... but apparently he doensn't use hooks anymore :/

Also, I found an use case for setting environment variables as well, but it was an instance of "cumbersome app configuration" that could have been (and was!) fixed by using sane defaults.

I'm not sure yet what would be the problem with the string interpolation that you mentioned, but I only skimmed the proposed changes. But if we both agree that doing it in python code is the way forward I'll pick that. At least now I know which usecases (just the env variables) for more than 1 person I can/have to cover.

I'll probably use something like the `VIRTUALENVWRAPPER_HOOK_DIR` (defaulting to `WORKON_HOME`) for the location of the hooks/customization

That file name could be something like `user_scripts.py`, `user.py`, `hooks.py` or something else

There'd be one such global file, and one for each env, and the file would probably look like this:

```python

env = {
  'CUSTOM_VAR': 'VAL'
}

def get_env_details(env):
  yadayada

def preactivate(env):
  yadayada


@priority(20)
def postrmvirtualenv(env):
  yadayada

```

I was thinking of using `@priority` to let the user specify in which order some hooks should be executed, rather than simply defining that the global hooks will be overridden (or executed before) the per-env hooks. but this latter alternative might be better

Also, obviously setting the environment variables can clash with the `.bashrc` (or the like) that gets sourced/executed by the subshell, but hopefully users should be aware of that and usually just define extra variables (rather than redefining things like `PATH`)

To execute random scripts/program, `subprocess.call` should be enough, so I don't plan to implicitly allow anything else than python scripts as hooks/program to be executed

This is just a quick comment that I wanted to write down. I've been quite busy lately, but this change is definitely one of the most interesting for me

**Comment by ryanhiebert** [comment]
FWIW, I like the idea of having a better thought out interface to environment variables in virtualenvs built-in to `pew`. My inclination is to use Forman-style `.env` files to control them, and not have any dynamism in them.

That doesn't preclude the possibility of python-file hooks, though. I don't have a problem with that idea either.

**Comment by DanMayhem** [comment]
I've been thinking about this pull request and issue #3 a lot over the last couple of days, reading about virtualenvwrapper hooks and looking for examples of how people use hooks (I've never used them myself).

Depending on which hook is being invoked, sometimes virtualenvwrapper sources the hook (e.g. postactivate) and sometimes it runs the hook in a child process (e.g. get_env_details). I'm curious about people's thoughts on running the hooks in the pew process or running them in a child process. 

Running the hooks within the pew process would allow the user to do things like setting environment variables or changing the working directory (although we'd need to think through the implications for the pew-inall command), but they wouldn't have access to the packages in the virtual environment or the virtual environment's version of python. Running the hooks in the pew process reduces the "environment variable problem" down to a straightforward user-provided script. Either based on the .inve.ini implementation, a Foreman-style .env implementation or simply altering os.environ.

Running the hooks as a child process (executed in the virtual environment) allows the user to work *in* the virtual environment and do things like starting a starting a development server or installing packages. In this approach setting environment variables would have to be handled as a special case.

Maybe the answer is to have some hooks run in the pew process and some run in the virtual environment?

I can prototype some options if it would be useful for discussion.

**Comment by rraval** [comment]
@DanMayhem Take a look at #47, which is one possible implementation of hooks. It allows for the definition of certain hooks that only run in the pew process and other hooks that run in the child process.

**Comment by DanMayhem** [comment]
superceded by #47

**Comment by berdario** [comment]
The discussion will go on on #47 but:

- the `pew setvar` proposal still needs to be evaluated (if we go with an all-python approach like I was planning it'll probably be rejected, but still...)
- All the hooks will be probably executed in-process: the `pew inall` aspect shouldn't be a problem, if hook-functions won't be used to modify environment variable (for that, either a `hooks.env` variable should be defined, or another configuration file should be used). But otoh, there's no simple way to guarantee that the user won't modify the env in such a function. Anyhow: by having in-process hooks it is possible to fork into subprocesses, while the converse wouldn't be possible. Also: depending on _where_ the hooks are actually invoked, I don't think that running in a subprocess would necessarily make it easy to `work in the virtual environment`

For that last concern, the easiest way imho is just to wrote a simple script that uses `pew in` (and obviously such a script could be forked out in one of those hooks)

**Comment by DanMayhem** [comment]
One of the use cases I found was to install packages in `postmkvirtualenv`, which I agree could be done with a `pew in`. But another use case was to start a local service on `postactivate`. Since I would expect `pew in` to call `postactivate` prior to executing the command, I don't think it makes sense to call `pew in` from `postactivate`.

In cases like this it would be nice to have the hook execute in a fully activated environment.

That of courses raises problems with the gists on #47 because those would have a dependency on pew - which may not be present in the virtual environment.

Or maybe we don't have a `postactivate` hook.

**Comment by berdario** [comment]
Yes, the postactivate hook would have to be completely different from any other hook, so I don't plan to implement it
-- 
Sent from mobile. Please excuse my brevity.

**Pull request closed without merging**
