### PR TITLE
PPA Support

### PR DESCRIPTION
**Pull request by kennethreitz**

### CODE REVIEW

**Comment by berdario** [comment]
Thank you.

I see that there was an appveyor failure, but master is clean. I'm on mobile, so I haven't checked yet properly... Did appveyor became flaky and unreliable for us?

**Comment by kennethreitz** [comment]
I think it was just because i merged before the tests passed.

FYI I uploaded the PPA to: https://launchpad.net/~kennethreitz/+archive/ubuntu/pipenv

**Comment by kennethreitz** [comment]
Unfortunately, to make this work, I had to change the author name to "Kenneth Reitz" in setup.py. Going to work to make that dynamic so when uploading it gets changed to your name.

**Comment by kennethreitz** [comment]
This is because of GPG keys.

**Pull request merged**
